# org: sandalboyz
# app: toolz-api
service:
  name: toolz-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x

functions:
  deleteProductsOnEasyPost:
    handler: handlers.deleteProductsOnEasyPostHandler
    cors: true
    events:
      - http: GET /deleteProductsOnEasyPost
      - http: 'GET /deleteProductsOnEasyPost/{proxy+}'
  getOrderReturnsStatus:
    handler: handlers.getOrderReturnsStatusHandler
    cors: true
    timeout: 15
    events:
      - http: GET /getOrderReturnsStatus
      - http: 'GET /getOrderReturnsStatus/{proxy+}'
  getTotalInventoryQuantity:
    handler: handlers.getTotalInventoryQuantityHandler
    cors: true
    events:
      - http: GET /getTotalInventoryQuantity
      - http: 'GET /getTotalInventoryQuantity/{proxy+}'
  syncInventories:
    handler: handlers.syncInventoriesHandler
    cors: true
    events:
      - http: GET /syncInventories
      - http: 'GET /syncInventories/{proxy+}'
